/**
 * Canadian University of Nigeria — structured public content catalogue.
 * Public facts are restricted to information corroborated by CUN's public site,
 * NUC records, and published institutional reports. Unpublished values are not invented.
 */
window.CUN_DATA = {
  university: {
    name: "Canadian University of Nigeria",
    shortName: "CUN",
    tagline: "Where Knowledge Meets Global Excellence",
    location: "Abuja, Federal Capital Territory, Nigeria",
    established: "2023",
    status: "Private university",
    regulatory: "National Universities Commission (NUC)",
    regulatoryStatus: "Listed by NUC among approved private universities; provisional operating licence issued in 2023.",
    proprietor: "Adamu Abubakar Gwarzo Foundation",
    supervisingInstitutionAtLicence: "Nile University, Abuja",
    address: "Abuja, Federal Capital Territory, Nigeria",
    plusCode: "3C7G+2MR, Utako, Abuja",
    email: "",
    phone: "",
    website: "https://www.cun.edu.ng/",
    social: {facebook:"",instagram:"",twitter:"",linkedin:"",youtube:"",whatsapp:""}
  },
  stats: [
    {label:"Established", value:"2023"},
    {label:"Institution", value:"Private University"},
    {label:"Location", value:"Abuja, FCT"},
    {label:"Regulator", value:"NUC"}
  ],
  faculties: [
    {id:"health", name:"Health Sciences", code:"HS", type:"Academic area", description:"One of the initial academic areas publicly reported for CUN, with health-related professional programmes.", programmes:["Physiotherapy","Public Health","Medical Laboratory Science","Nursing"]},
    {id:"computing", name:"School of Computing", code:"SC", type:"School", description:"The initial computing academic area publicly reported for CUN.", programmes:["Cyber Security","Information Technology","Data Science","Computer Science"]},
    {id:"management-social", name:"Management & Social Sciences", code:"MSS", type:"Academic area", description:"The initial management and social sciences academic area publicly reported for CUN.", programmes:["Banking & Finance","Business Administration","Human Resource Management","Mass Communication"]}
  ],
  departments: [
    {id:"health-sciences", faculty:"health", name:"Health Sciences", programmes:["physiotherapy","public-health","medical-laboratory","nursing"]},
    {id:"computing", faculty:"computing", name:"Computing", programmes:["cyber-security","information-technology","data-science","computer-science"]},
    {id:"management-social-sciences", faculty:"management-social", name:"Management & Social Sciences", programmes:["banking-finance","business-admin","human-resource","mass-communication"]}
  ],
  programmes: [
    {id:"physiotherapy",name:"Physiotherapy",faculty:"health",department:"health-sciences",degree:"Professional undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial Health Sciences programmes.",requirements:"Meet the current university and regulatory entry requirements for the programme. Exact subject combinations and cut-off requirements should be taken from the current CUN admissions notice.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Physiotherapy and rehabilitation practice"},
    {id:"public-health",name:"Public Health",faculty:"health",department:"health-sciences",degree:"Undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial Health Sciences programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Public health and community health programmes"},
    {id:"medical-laboratory",name:"Medical Laboratory Science",faculty:"health",department:"health-sciences",degree:"Professional undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial Health Sciences programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Medical laboratory practice and diagnostics"},
    {id:"nursing",name:"Nursing",faculty:"health",department:"health-sciences",degree:"Professional undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial Health Sciences programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Nursing and clinical care"},
    {id:"cyber-security",name:"Cyber Security",faculty:"computing",department:"computing",degree:"Undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial computing programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Cybersecurity, security operations and information assurance"},
    {id:"information-technology",name:"Information Technology",faculty:"computing",department:"computing",degree:"Undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial computing programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"IT operations, systems and technology services"},
    {id:"data-science",name:"Data Science",faculty:"computing",department:"computing",degree:"Undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial computing programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Data analysis, analytics and technology"},
    {id:"computer-science",name:"Computer Science",faculty:"computing",department:"computing",degree:"Undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial computing programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Software, computing and technology"},
    {id:"banking-finance",name:"Banking & Finance",faculty:"management-social",department:"management-social-sciences",degree:"Undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial management and social sciences programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Banking, finance and financial services"},
    {id:"business-admin",name:"Business Administration",faculty:"management-social",department:"management-social-sciences",degree:"Undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial management and social sciences programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Business, management and entrepreneurship"},
    {id:"human-resource",name:"Human Resource Management",faculty:"management-social",department:"management-social-sciences",degree:"Undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial management and social sciences programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Human resources and organisational management"},
    {id:"mass-communication",name:"Mass Communication",faculty:"management-social",department:"management-social-sciences",degree:"Undergraduate programme",duration:"Programme-specific duration is set by the approved curriculum",mode:"Full-time",overview:"Publicly reported among CUN's initial management and social sciences programmes.",requirements:"Meet the current university and regulatory entry requirements. Confirm the current subject combination and cut-off with Admissions.",utme:"Current JAMB/UTME and programme-specific requirements apply.",directEntry:"Direct Entry eligibility is determined by the current CUN admissions policy and relevant regulatory requirements.",careers:"Media, communications and public relations"}
  ],
  news: [
    {id:"nuc-licence-2023",title:"Canadian University of Nigeria listed among Nigeria's private universities",category:"Institutional",date:"2023-11-15",image:"assets/images/campus-hero.jpg",excerpt:"The National Universities Commission lists Canadian University of Nigeria, Abuja among approved private universities. The NUC record dates the institution to 2023.",source:"National Universities Commission"},
    {id:"initial-programmes",title:"CUN's initial academic programmes span health, computing and management",category:"Academics",date:"2023-11-15",image:"assets/images/lecture.jpg",excerpt:"Published reports on the university's launch identified initial programmes across Health Sciences, Computing, and Management & Social Sciences.",source:"Published institutional launch reports"},
    {id:"abuja-campus",title:"Canadian University of Nigeria establishes its academic base in Abuja",category:"University Update",date:"2023-06-01",image:"assets/images/abuja.jpg",excerpt:"Public records and launch coverage place Canadian University of Nigeria in Abuja, Federal Capital Territory.",source:"NUC and public launch records"}
  ],
  events: [
    {id:"licence-2023",title:"NUC provisional licence milestone",category:"Institutional milestone",date:"2023-06-01",time:"",location:"Abuja, FCT",description:"The university's establishment and provisional operating licence were recorded by the National Universities Commission in 2023."},
    {id:"academic-launch-2024",title:"Academic activities launch period",category:"Academic milestone",date:"2024-09-01",time:"",location:"Abuja, FCT",description:"Public reports from 2023 stated that CUN planned to commence academic activities in September 2024."}
  ],
  faqs: [
    {category:"Admissions",q:"How do I start an application?",a:"Use the Apply Now workflow to create or continue an application. You will be able to select a programme, enter your details, upload documents and submit the application."},
    {category:"Admissions",q:"Does CUN accept UTME and Direct Entry applicants?",a:"Public launch reports identify undergraduate admission through UTME and Direct Entry pathways. Always use the current CUN admission notice for the exact requirements for your programme."},
    {category:"Programmes",q:"Which programmes are publicly reported for CUN?",a:"The public launch record identifies programmes in Health Sciences, Computing, and Management & Social Sciences. The Programmes directory on this site groups those publicly reported offerings by academic area."},
    {category:"Fees",q:"Where can I find the current fee schedule?",a:"The public CUN website does not currently publish a complete fee schedule. This platform therefore does not invent fee figures. Students should use the official fee statement supplied through their authenticated portal or contact the university's admissions/bursary office."},
    {category:"Portals",q:"What can the student portal do?",a:"Authenticated students can view their profile, applications, course registrations, results, fee records, payments and application documents. Availability of a feature depends on the student's records and the permissions configured in Supabase."},
    {category:"University",q:"Where is CUN located?",a:"Canadian University of Nigeria is located in Abuja, Federal Capital Territory, Nigeria. Public listings identify Utako, Abuja as the campus location."},
    {category:"Accreditation",q:"Is CUN recognised by the NUC?",a:"The National Universities Commission lists Canadian University of Nigeria, Abuja among Nigeria's private universities and recorded its establishment in 2023. Programme-level accreditation should be checked against the current NUC record for the specific programme."}
  ]
};
